# Generated by Django 4.2.10 on 2024-02-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_activityexperience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityexperience",
            name="end_date",
            field=models.DateField(blank=True, default="2000-01-01", null=True),
        ),
        migrations.AlterField(
            model_name="activityexperience",
            name="start_date",
            field=models.DateField(blank=True, default="2000-01-01", null=True),
        ),
    ]
