# Generated by Django 4.2.10 on 2024-03-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_student_name_alter_student_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="grade",
            field=models.IntegerField(
                choices=[
                    (10, "Year 10"),
                    (11, "Year 11"),
                    (12, "Year 12"),
                    (13, "Year 13"),
                ]
            ),
        ),
    ]
