# Generated by Django 4.2.10 on 2024-05-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0007_student_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="ib_ia_title",
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="ib_subject",
            field=models.TextField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="recommendation",
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="strength",
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="weakness",
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
