# Generated by Django 4.2.10 on 2024-02-12 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_customuser_groups_customuser_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="category",
        ),
        migrations.AddField(
            model_name="activity",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manager.category",
            ),
        ),
    ]
