# Generated by Django 4.2.10 on 2024-05-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0004_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
