# Generated by Django 4.2.10 on 2024-06-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0005_activity_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
